spring.application.name=banquito-clearinghouse-service
server.port=${SERVER_PORT:8087}

spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}
spring.mongodb.uri=${SPRING_DATA_MONGODB_URI}

spring.mongodb.host=${MONGODB_HOST}
spring.mongodb.port=${MONGODB_PORT:27017}
spring.mongodb.database=${MONGODB_DATABASE}

pubsub.project-id=${PUBSUB_PROJECT_ID:${GCP_PROJECT_ID}}
pubsub.subscription.clearing-outbound=${PUBSUB_SUBSCRIPTION_CLEARING_OUTBOUND:clearing-outbound-sub}

core.service.settlement-url=${CORE_GATEWAY_URL}/api/v2/payments/offus-settlement

compensation.output.dir=${COMPENSATION_OUTPUT_DIR:}

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.health.mongodb.enabled=${MANAGEMENT_HEALTH_MONGO_ENABLED:false}

logging.level.root=INFO
logging.level.org.springframework.data.mongodb=INFO
