# ==========================================
# APP
# ==========================================

spring.application.name=banquito-clearinghouse-adapter

server.port=8087

# ==========================================
# MONGODB
# ==========================================

spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=clearingdb

# Alternativa URI
# spring.data.mongodb.uri=mongodb://localhost:27017/clearingdb

# ==========================================
# RABBITMQ
# ==========================================

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

rabbitmq.clearing.queue=clearing.outbound.queue

# ==========================================
# ACCOUNTING SERVICE (BRYAN)
# ==========================================

core.accounting.url=http://localhost:8010/api/v2/accounting/entries

# Si usan Kong Core:
# core.accounting.url=http://kong-core:8000/api/v2/accounting/entries

# ==========================================
# ACTUATOR
# ==========================================

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# ==========================================
# LOGGING
# ==========================================

logging.level.root=INFO
logging.level.org.springframework.amqp=INFO
logging.level.org.springframework.data.mongodb=INFO

# ==========================================
# JACKSON
# ==========================================

spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false